// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';

const SUPABASE_URL = "https://bqynzvudrpexjmstikno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxeW56dnVkcnBleGptc3Rpa25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTY5OTEsImV4cCI6MjA3MzY3Mjk5MX0.LjaLr3uQVMp9F5YJfHMBwjqC0rIlqoBiylUA9Rdy6Kc";

// Lazy-load Supabase client from CDN to avoid bundler resolution issues
let clientPromise: Promise<any> | null = null;

async function createClientLazy() {
  const url = 'https://esm.sh/@supabase/supabase-js@2.57.4?bundle&target=esnext';
  const mod: any = await import(/* @vite-ignore */ url);
  const createClient = mod.createClient as (<T>(url: string, key: string, opts?: any) => any);
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

export async function getSupabase() {
  if (!clientPromise) clientPromise = createClientLazy();
  return clientPromise;
}

// Usage:
// const supabase = await getSupabase();
